### PR TITLE
Apache Kafka version update with one shot commit

### LINKED ISSUE #70: Align KNet to latest Apache Kafka version
**Is your feature request related to a problem? Please describe.**
The main version of Apache Kafka has evolved to _3.2.0_, the project is aligned to the patch _3.1.1_.

**Describe the solution you'd like**
Align the project to the latest version of Apache Kafka

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by masesdevelopers**
## Description
Apache Foundation released the version 3.2.0 of Apache Kafka. This PR updates KNet to the latest version of Apache Kafka.

## Related Issue

closed #70 

## Motivation and Context

Align KNet to the latest version which solves bugs and introduces new functionality: see https://downloads.apache.org/kafka/3.2.0/RELEASE_NOTES.html

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by mariomastrodicasa — CHANGES_REQUESTED** [review]
The configuration files hasn't changed? Have you checked the source code diff to verify API changes?

**Comment by masesdevelopers** [comment]
> The configuration files hasn't changed? 

Some minor changes are available in the configuration files. Mainly in **kraft**.

> Have you checked the source code diff to verify API changes?

Yes, there are some changes

**Comment by mariomastrodicasa** [comment]
I opened a new issue (#70) to track the alignment to the latest Apache Kakfa version.

**Comment by masesdevelopers** [comment]
> > > The configuration files hasn't changed?
> > 
> > 
> > Some minor changes are available in the configuration files. Mainly in **kraft**.
> 
> Update the files

Configuration files aligned

> 
> > > Have you checked the source code diff to verify API changes?
> > 
> > 
> > Yes, there are some changes
> 
> We need to align the code: the HEAD of master is aligned to the patch 3.1.1. We have to continue to use that version until the API are aligned to the version 3.2.0.

The PR now covers the changes identified using a source tree compare.

**Comment by mariomastrodicasa** [comment]
> > > > The configuration files hasn't changed?
> > > 
> > > 
> > > Some minor changes are available in the configuration files. Mainly in **kraft**.
> > 
> > 
> > Update the files
> 
> Configuration files aligned
> 
> > > > Have you checked the source code diff to verify API changes?
> > > 
> > > 
> > > Yes, there are some changes
> > 
> > 
> > We need to align the code: the HEAD of master is aligned to the patch 3.1.1. We have to continue to use that version until the API are aligned to the version 3.2.0.
> 
> The PR now covers the changes identified using a source tree compare.

If the changes are only incremental this PR can be merged into master and the version 1.3.0 will directly move to Apache Kafka version 3.2.0.

**Review by mariomastrodicasa — APPROVED** [review]

**Pull request merged**
